version: '2'
services:
    freedom:
        image: breakfree:latest
        container_name: breakfree
        ports: 
            - "8080:80"
        links:
            - mongodb
    mongodb:
        image: mongo:3.2 
        container_name: mongodb
